name: super_tic_tac_toe
description: A Super Tic-Tac-Toe game built with Flutter.
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    # Add any images, fonts, or other assets here if needed in the future
    # Example:
    # - images/
